Repository jakubriegel/PUT_Eli_OS, pull requests merged in 2018-11, with the labels that each got.

#5 Shell integration
  src/main/java/AppStart.java
  src/main/java/System.java
  src/main/java/shell/Commands.java
  src/main/java/shell/Shell.java
  src/main/java/utils/CustomOutputStream.java
  src/main/java/utils/Utils.java
Labels: needs discussion

#4 assembler init, added base integration with PCB
  .gitignore
  build.gradle
  src/main/java/assembler/ArgumentTypes.java
  src/main/java/assembler/Assembler.java
  src/main/java/assembler/AssemblerUtils.java
  src/main/java/assembler/CPU.java
  src/main/java/assembler/CPUState.java
  src/main/java/assembler/Instruction.java
  src/main/java/assembler/Registry.java
  src/main/java/processess/PCB.java
  src/main/java/processess/PCBList.java
  src/test/groovy/assembler/AssemblerSpecification.groovy
  src/test/groovy/assembler/InstructionSpecification.groovy
Labels: enhancement, needs discussion

#7 Assembler | wprowadzone lokowanie pamięci i nowa metoda dla stanów procesora
  src/main/java/assembler/Assembler.java
  src/main/java/assembler/AssemblerUtils.java
  src/main/java/assembler/CPUState.java
  src/main/java/assembler/Instruction.java
  src/main/java/processess/PCB.java
  src/main/resources/assembler/factorial_16.asm
  src/main/resources/assembler/factorial_8.asm
  src/test/groovy/assembler/AssemblerSpecification.groovy
Labels: enhancement
