Repository jakubriegel/PUT_Eli_OS, pull requests merged in 2019-01, with the labels that each got.

#23 Synchronization
  src/main/java/processess/PCBList.java
  src/main/java/synchronization/LockFunction.java
  src/test/groovy/synchronization/LockFunctionSpecification.groovy
Labels: IMPORTANT

#25 Integracja z synchronizacją i przykładowe programy
  src/main/java/assembler/Assembler.java
  src/main/java/assembler/Instruction.java
  src/main/java/filesystem/Files.java
  src/main/java/os/OS.java
  src/main/java/processess/PCB.java
  src/main/java/processess/PCBList.java
  src/main/java/processor/Processor.java
  src/main/java/shell/Commands.java
  src/main/java/shell/Shell.java
  src/main/java/synchronization/Lock.java
  src/main/java/synchronization/LockFunction.java
  src/main/resources/assembler/cp.asm
  src/main/resources/assembler/f8.asm
  src/main/resources/assembler/files.asm
  src/main/resources/assembler/get.asm
  src/main/resources/assembler/prc.asm
  src/test/groovy/synchronization/LockFunctionSpecification.groovy
Labels: IMPORTANT

#21 Memory + VM Integration
  src/main/java/memory/Memory.java
  src/main/java/virtualmemory/virtualmemory.java
Labels: IMPORTANT, needs discussion, not ready

#24 Shell
  src/main/java/AppStart.java
  src/main/java/filesystem/Directories.java
  src/main/java/filesystem/Files.java
  src/main/java/shell/Commands.java
  src/main/java/shell/Shell.java
  src/main/java/utils/Utils.java
Labels: enhancement

#32 Shell - tree command
  src/main/java/filesystem/Directory.java
  src/main/java/memory/Memory.java
  src/main/java/shell/Commands.java
  src/main/java/shell/Shell.java
Labels: enhancement
